redis:
  host: localhost
  port: 6379
  password: 123456
  database: 1
  timeout: 2000ms  # 连接超时时间（毫秒）默认是2000ms
  lettuce:
    pool:
      max-active: 200  # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 100 # 连接池中的最大空闲连接
      min-idle: 50 # 连接池中的最小空闲连接
    shutdown-timeout: 100ms
#    sentinel:  # 哨兵模式
#      master: mymaster
#      nodes: 192.168.222.155:26379,192.168.222.155:26380,192.168.222.155:26381