server:
  port: 8999
spring:
  profiles:
    active: local
  devtools:
    restart:
      enabled: true
  session:
    store-type: none
    timeout: 3600s
  thymeleaf:
    prefix: classpath:/templates/
    mode: LEGACYHTML5
    encoding: UTF-8
    cache: false
    suffix: .html

  mvc:
    static-path-pattern: /**
    throw-exception-if-no-handler-found: true
  #  resources:
#    static-locations: classpath:/templates/,classpath:/static/
  web:
    resources:
      static-locations: classpath:/templates/,classpath:/static/

#mybatis配置
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.education.domain
  global-config:
    db-config:
      id-type: auto
      table-underline: true
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true

#logback输出日志配置
logging:
  config:
    classpath: logback-spring.xml